import 'package:flutter/material.dart';

class LanguageScope extends InheritedWidget {
  final String language;
  final ValueChanged<String> onLanguageChanged;

  const LanguageScope({
    super.key,
    required this.language,
    required this.onLanguageChanged,
    required super.child,
  });

  static LanguageScope? of(BuildContext context) {
    return context.dependOnInheritedWidgetOfExactType<LanguageScope>();
  }

  @override
  bool updateShouldNotify(LanguageScope old) => old.language != language;
}

String t(BuildContext context, String key) {
  final lang = LanguageScope.of(context)?.language ?? 'en';
  return AppTranslations.get(lang, key);
}

class SupportedLanguage {
  final String code;
  final String name;
  final String nativeName;
  final String ttsLocale;

  const SupportedLanguage({
    required this.code,
    required this.name,
    required this.nativeName,
    required this.ttsLocale,
  });
}

const List<SupportedLanguage> supportedLanguages = [
  SupportedLanguage(code: 'en', name: 'English', nativeName: 'English', ttsLocale: 'en-IN'),
  SupportedLanguage(code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', ttsLocale: 'hi-IN'),
  SupportedLanguage(code: 'mr', name: 'Marathi', nativeName: 'मराठी', ttsLocale: 'mr-IN'),
  SupportedLanguage(code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', ttsLocale: 'kn-IN'),
  SupportedLanguage(code: 'te', name: 'Telugu', nativeName: 'తెలుగు', ttsLocale: 'te-IN'),
  SupportedLanguage(code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', ttsLocale: 'ta-IN'),
];

class AppTranslations {
  AppTranslations._();

  static String get(String lang, String key) {
    return _translations[lang]?[key] ?? _translations['en']?[key] ?? key;
  }

  static final Map<String, Map<String, String>> _translations = {
    'en': {
      'nav_scan': 'Scan',
      'nav_result': 'Result',
      'nav_treat': 'Treat',
      'nav_history': 'History',
      'home_hint': 'Point at the affected leaf',
      'home_gallery': 'Gallery',
      'home_take_photo': 'Take Photo',
      'weather_msg': 'High humidity today — risk of fungus',
      'disease_detected': 'Disease Detected',
      'found_on': 'Found on',
      'match': 'match',
      'needs_attention': 'Needs Attention',
      'critical': 'Critical',
      'monitor': 'Monitor',
      'healthy': 'Healthy',
      'see_what_to_do': 'See What To Do',
      'treatment_plan': 'Treatment Plan',
      'what_to_do': 'What to do now',
      'maintenance_tips': 'Maintenance Tips',
      'buy_nearby': 'Buy nearby',
      'get_directions': 'Get Directions',
      'do_today': 'Do today',
      'ongoing': 'Ongoing',
      'step1': 'Spray Mancozeb solution before sunset today',
      'step1_detail': 'Mix 2.5g per litre of water. Spray on all leaves, top and bottom.',
      'step2': 'Remove the 3-4 most affected leaves',
      'step2_detail': 'Cut them off and take them away from the field. Don\'t leave them on the ground.',
      'step3': 'Water at the base only — avoid wetting leaves',
      'step3_detail': 'Use drip irrigation or pour water directly at the roots. Wet leaves help the fungus grow.',
      'crop_history': 'Crop History',
      'history_subtitle': 'Your field health over time',
      'recent_scans': 'Recent Scans',
      'scans': 'Scans',
      'active': 'Active',
      'treated': 'Treated',
      'diseases': 'Diseases',
      'resolved': 'Resolved',
      'status_active': 'Active',
      'status_fixed': 'Fixed',
      'status_ok': 'OK',
      'field_health': 'Field Health',
      'watch': 'Watch',
      'affected': 'Affected',
      'early_blight': 'Early Blight',
      'early_blight_sci': 'Alternaria solani',
      'early_blight_desc': 'This fungus makes round brown spots with rings on the leaves. It starts on the older leaves at the bottom and spreads upward.',
      'early_blight_spread': 'Spreads fast in humid weather, especially when leaves stay wet overnight.',
      'early_blight_urgency': 'Act within 24 hours — this spreads quickly in wet conditions.',
      'confidence': 'Confidence',
      'scan_details': 'Scan Details',
      'treatment_applied': 'Treatment Applied',
      'no_treatment': 'No treatment recorded',
      'view_treatment': 'View Treatment',
      'language': 'Language',
      'listening': 'Listening...',
      'tomato': 'Tomato',
      'onion': 'Onion',
      'soybean': 'Soybean',
      'cotton': 'Cotton',
      'late_blight': 'Late Blight',
      'powdery_mildew': 'Powdery Mildew',
      'bacterial_blight': 'Bacterial Blight',
      'nav_community': 'Feed',
      'community_alerts': 'Community Alerts',
      'community_subtitle': 'Disease reports near your farm',
      'reports_near_you': 'Disease reports near you',
      'reports_nearby': 'reports nearby',
      'this_week_5km': 'This week within 5 km',
      'trending_diseases': 'Trending Diseases',
      'recent_reports': 'Recent Reports',
      'your_field': 'Your Field',
      'radius': 'radius',
      'ago': 'ago',
      'spray_schedule': 'Spray Schedule',
      'harvest_window': 'Safe harvest window opens in ~21 days',
      'track_recovery': 'Track Recovery',
      'before': 'Before',
      'after': 'After',
      'drag_to_compare': 'Drag the slider to compare before and after',
      'offline_mode': 'Offline mode',
      'scans_saved': 'scans saved locally',
      'syncing_scans': 'Back online — syncing scans...',
      'back_online': 'All synced!',
      'report_disease': 'Report Disease',
      'report_help_text': 'Help nearby farmers by reporting diseases in your field',
      'select_crop': 'Select Crop',
      'select_disease': 'Select Disease',
      'submit_report': 'Submit Report',
      'report_submitted': 'Your report has been shared with nearby farmers!',
      'you': 'You',
      'wheat': 'Wheat',
      'rice': 'Rice',
      'leaf_curl': 'Leaf Curl',
      'root_rot': 'Root Rot',
      'voice_tap_to_speak': 'Tap to speak',
      'voice_listening': 'Listening...',
      'voice_processing': 'Processing...',
      'voice_result': 'You said:',
      'voice_error': 'Could not understand, try again',
      'voice_no_mic': 'Please allow microphone access',
      'voice_retry': 'Retry',
      'voice_close': 'Close',
      'voice_followup_treatment': 'Say "Show treatment"',
      'voice_followup_home': 'Say "Go to home"',
      'voice_followup_scan': 'Say "Scan leaf"',
      'voice_followup_history': 'Say "Show history"',
      'home_diagnostic_scan': 'Diagnostic Scan',
      'home_gallery': 'Gallery',
      'home_take_photo': 'Take Photo',
      'home_log_action': "Log Today's Action",
      'home_target_crop': 'Target Crop',
      'home_action_type': 'Action Type',
      'home_quick_note': 'Quick Note',
      'home_note_hint': 'E.g., Added 2kg of NPK...',
      'home_save_log': 'Save Log',
      'home_log_saved': 'Log saved successfully!',
      'history_action_logs': 'Action Logs',
      'history_no_logs': 'No logs recorded yet',
      'history_no_scans': 'No scans this season',
      'history_season_kharif': 'Kharif',
      'history_season_rabi': 'Rabi',
      'community_helpline': 'Emergency Helpline',
      'community_helpline_kvk': 'Krishi Vigyan Kendra',
      'community_helpline_kvk_subtitle': 'Agricultural Science Center',
      'community_helpline_kcc': 'Kisan Call Center',
      'community_helpline_kcc_subtitle': "Govt. Agri Helpline (Toll-Free)",
      'community_helpline_ppa': 'Plant Protection Advisor',
      'community_helpline_ppa_subtitle': 'District Agriculture Officer',
      'community_call': 'Call',
      'treatment_baramati': 'Baramati',
      'step_done': 'Done',
      'log_saved': 'Log saved successfully!',
      'season_kharif': 'Kharif',
      'season_rabi': 'Rabi',
      'disease_map_title': 'Disease Map',
      'area_affected': 'area affected',
      'hide_mask': 'Hide',
      'show_mask': 'Show',
      'severity_level': 'Severity Level',
      'analyzing_affected_area': 'Analyzing affected area...',
    },
    'hi': {
      'nav_scan': 'स्कैन',
      'nav_result': 'नतीजा',
      'nav_treat': 'इलाज',
      'nav_history': 'इतिहास',
      'home_hint': 'प्रभावित पत्ते की ओर कैमरा करें',
      'home_gallery': 'गैलरी',
      'home_take_photo': 'फोटो लें',
      'weather_msg': 'आज नमी ज़्यादा है — फफूंद का खतरा',
      'disease_detected': 'रोग पाया गया',
      'found_on': 'पाया गया',
      'match': 'मैच',
      'needs_attention': 'ध्यान दें',
      'critical': 'गंभीर',
      'monitor': 'निगरानी',
      'healthy': 'स्वस्थ',
      'see_what_to_do': 'क्या करें देखें',
      'treatment_plan': 'इलाज योजना',
      'what_to_do': 'अभी क्या करें',
      'maintenance_tips': 'रखरखाव सुझाव',
      'buy_nearby': 'पास में खरीदें',
      'get_directions': 'रास्ता देखें',
      'do_today': 'आज करें',
      'ongoing': 'जारी रखें',
      'step1': 'आज सूरज डूबने से पहले मैन्कोज़ेब का घोल छिड़कें',
      'step1_detail': '2.5 ग्राम प्रति लीटर पानी में मिलाएं। सभी पत्तों पर ऊपर-नीचे छिड़कें।',
      'step2': 'सबसे ज़्यादा प्रभावित 3-4 पत्ते तोड़ दें',
      'step2_detail': 'उन्हें काटकर खेत से दूर ले जाएं। ज़मीन पर न छोड़ें।',
      'step3': 'सिर्फ जड़ में पानी दें — पत्तों को गीला न करें',
      'step3_detail': 'ड्रिप सिंचाई का उपयोग करें। गीले पत्ते फफूंद बढ़ाते हैं।',
      'crop_history': 'फसल इतिहास',
      'history_subtitle': 'आपके खेत की सेहत',
      'recent_scans': 'हाल के स्कैन',
      'scans': 'स्कैन',
      'active': 'सक्रिय',
      'treated': 'उपचारित',
      'diseases': 'रोग',
      'resolved': 'ठीक हुआ',
      'status_active': 'सक्रिय',
      'status_fixed': 'ठीक',
      'status_ok': 'ठीक',
      'field_health': 'खेत स्वास्थ्य',
      'watch': 'नज़र रखें',
      'affected': 'प्रभावित',
      'early_blight': 'अगेती झुलसा',
      'early_blight_sci': 'Alternaria solani',
      'early_blight_desc': 'यह फफूंद पत्तों पर गोल भूरे धब्बे बनाती है। यह नीचे के पुराने पत्तों से शुरू होकर ऊपर फैलती है।',
      'early_blight_spread': 'गीले मौसम में तेज़ी से फैलती है, खासकर जब पत्ते रात भर गीले रहें।',
      'early_blight_urgency': '24 घंटे में इलाज करें — गीले मौसम में तेज़ी से फैलता है।',
      'confidence': 'विश्वसनीयता',
      'scan_details': 'स्कैन विवरण',
      'treatment_applied': 'उपचार किया गया',
      'no_treatment': 'कोई उपचार दर्ज नहीं',
      'view_treatment': 'उपचार देखें',
      'language': 'भाषा',
      'listening': 'सुन रहे हैं...',
      'tomato': 'टमाटर',
      'onion': 'प्याज',
      'soybean': 'सोयाबीन',
      'cotton': 'कपास',
      'late_blight': 'पछेती झुलसा',
      'powdery_mildew': 'चूर्णी फफूंद',
      'bacterial_blight': 'जीवाणु झुलसा',
      'nav_community': 'फीड',
      'community_alerts': 'समुदाय अलर्ट',
      'community_subtitle': 'आपके खेत के पास रोग रिपोर्ट',
      'reports_near_you': 'आपके पास रोग रिपोर्ट',
      'reports_nearby': 'रिपोर्ट पास में',
      'this_week_5km': 'इस हफ्ते 5 कि.मी. के अंदर',
      'trending_diseases': 'चलन में रोग',
      'recent_reports': 'हाल की रिपोर्ट',
      'your_field': 'आपका खेत',
      'radius': 'दायरा',
      'ago': 'पहले',
      'spray_schedule': 'छिड़काव कार्यक्रम',
      'harvest_window': 'सुरक्षित कटाई ~21 दिन में',
      'track_recovery': 'रिकवरी देखें',
      'before': 'पहले',
      'after': 'बाद में',
      'drag_to_compare': 'तुलना के लिए स्लाइडर खींचें',
      'offline_mode': 'ऑफलाइन मोड',
      'scans_saved': 'स्कैन सेव हैं',
      'syncing_scans': 'ऑनलाइन — स्कैन सिंक हो रहे हैं...',
      'back_online': 'सब सिंक हो गया!',
      'report_disease': 'रोग रिपोर्ट करें',
      'report_help_text': 'अपने खेत में रोग की रिपोर्ट करके पास के किसानों की मदद करें',
      'select_crop': 'फसल चुनें',
      'select_disease': 'रोग चुनें',
      'submit_report': 'रिपोर्ट भेजें',
      'report_submitted': 'आपकी रिपोर्ट पास के किसानों को भेजी गई!',
      'you': 'आप',
      'wheat': 'गेहूं',
      'rice': 'चावल',
      'leaf_curl': 'पत्ता मुड़ना',
      'root_rot': 'जड़ सड़न',
      'voice_tap_to_speak': 'बोलने के लिए दबाएं',
      'voice_listening': 'सुन रहे हैं...',
      'voice_processing': 'समझ रहे हैं...',
      'voice_result': 'आपने कहा:',
      'voice_error': 'समझ नहीं आया, फिर से बोलें',
      'voice_no_mic': 'माइक्रोफ़ोन की अनुमति दें',
      'voice_retry': 'फिर से कोशिश करें',
      'voice_close': 'बंद करें',
      'voice_followup_treatment': 'कहें "इलाज दिखाएं"',
      'voice_followup_home': 'कहें "होम पर जाएं"',
      'voice_followup_scan': 'कहें "पत्ता स्कैन करें"',
      'voice_followup_history': 'कहें "इतिहास दिखाएं"',
      'home_diagnostic_scan': 'डायग्नोस्टिक स्कैन',
      'home_gallery': 'गैलरी',
      'home_take_photo': 'फोटो लें',
      'home_log_action': 'आज की कार्रवाई लॉग करें',
      'home_target_crop': 'लक्ष्य फसल',
      'home_action_type': 'कार्रवाई प्रकार',
      'home_quick_note': 'त्वरित नोट',
      'home_note_hint': 'जैसे, 2kg NPK जोड़ा...',
      'home_save_log': 'लॉग सहेजें',
      'home_log_saved': 'लॉग सफलतापूर्वक सहेजा गया!',
      'history_action_logs': 'कार्रवाई लॉग',
      'history_no_logs': 'अभी तक कोई लॉग नहीं',
      'history_no_scans': 'इस मौसम में कोई स्कैन नहीं',
      'history_season_kharif': 'खरीफ',
      'history_season_rabi': 'रबी',
      'community_helpline': 'आपातकालीन हेल्पलाइन',
      'community_helpline_kvk': 'कृषि विज्ञान केंद्र',
      'community_helpline_kvk_subtitle': 'कृषि विज्ञान केंद्र',
      'community_helpline_kcc': 'किसान कॉल सेंटर',
      'community_helpline_kcc_subtitle': 'सरकारी कृषि हेल्पलाइन (नि:शुल्क)',
      'community_helpline_ppa': 'पौधे संरक्षण सलाहकार',
      'community_helpline_ppa_subtitle': 'जिला कृषि अधिकारी',
      'community_call': 'कॉल करें',
      'treatment_baramati': 'बारामती',
      'step_done': 'हो गया',
      'log_saved': 'लॉग सफलतापूर्वक सहेजा गया!',
      'season_kharif': 'खरीफ',
      'season_rabi': 'रबी',
      'disease_map_title': 'रोग का नक्शा',
      'area_affected': 'प्रभावित क्षेत्र',
      'hide_mask': 'छुपाएं',
      'show_mask': 'दिखाएं',
      'severity_level': 'गंभीरता का स्तर',
      'analyzing_affected_area': 'प्रभावित क्षेत्र की जांच हो रही है...',
    },
    'mr': {
      'nav_scan': 'स्कॅन',
      'nav_result': 'निकाल',
      'nav_treat': 'उपचार',
      'nav_history': 'इतिहास',
      'home_hint': 'प्रभावित पानाकडे कॅमेरा करा',
      'home_gallery': 'गॅलरी',
      'home_take_photo': 'फोटो काढा',
      'weather_msg': 'आज हवेत ओलावा जास्त — बुरशीचा धोका',
      'disease_detected': 'रोग आढळला',
      'found_on': 'आढळले',
      'match': 'जुळणी',
      'needs_attention': 'लक्ष द्या',
      'critical': 'गंभीर',
      'monitor': 'लक्ष ठेवा',
      'healthy': 'निरोगी',
      'see_what_to_do': 'काय करावे ते पहा',
      'treatment_plan': 'उपचार योजना',
      'what_to_do': 'आत्ता काय करावे',
      'maintenance_tips': 'देखभाल टिप्स',
      'buy_nearby': 'जवळपास खरेदी करा',
      'get_directions': 'मार्ग दाखवा',
      'do_today': 'आज करा',
      'ongoing': 'चालू ठेवा',
      'step1': 'आज सूर्यास्तापूर्वी मॅन्कोझेब फवारणी करा',
      'step1_detail': '2.5 ग्रॅम प्रति लिटर पाण्यात मिसळा. सर्व पानांवर वर-खाली फवारा.',
      'step2': 'सर्वात जास्त प्रभावित 3-4 पाने काढून टाका',
      'step2_detail': 'ती कापून शेतापासून दूर न्या. जमिनीवर सोडू नका.',
      'step3': 'फक्त मुळाशी पाणी द्या — पाने ओले करू नका',
      'step3_detail': 'ठिबक सिंचन वापरा. ओले पाने बुरशी वाढवतात.',
      'crop_history': 'पीक इतिहास',
      'history_subtitle': 'तुमच्या शेताचे आरोग्य',
      'recent_scans': 'अलीकडील स्कॅन',
      'scans': 'स्कॅन',
      'active': 'सक्रिय',
      'treated': 'उपचार',
      'diseases': 'रोग',
      'resolved': 'निराकरण',
      'status_active': 'सक्रिय',
      'status_fixed': 'दुरुस्त',
      'status_ok': 'ठीक',
      'field_health': 'शेत आरोग्य',
      'watch': 'लक्ष ठेवा',
      'affected': 'प्रभावित',
      'early_blight': 'लवकर करपा',
      'early_blight_sci': 'Alternaria solani',
      'early_blight_desc': 'हा बुरशीजन्य रोग पानांवर गोलाकार तपकिरी डाग बनवतो. तो खालच्या जुन्या पानांपासून सुरू होतो.',
      'early_blight_spread': 'ओलसर हवामानात वेगाने पसरतो, विशेषतः पाने रात्रभर ओली राहिल्यास.',
      'early_blight_urgency': '24 तासांत उपचार करा — ओलसर हवामानात वेगाने पसरतो.',
      'confidence': 'विश्वासार्हता',
      'scan_details': 'स्कॅन तपशील',
      'treatment_applied': 'केलेला उपचार',
      'no_treatment': 'उपचार नोंदलेला नाही',
      'view_treatment': 'उपचार पहा',
      'language': 'भाषा',
      'listening': 'ऐकत आहे...',
      'tomato': 'टोमॅटो',
      'onion': 'कांदा',
      'soybean': 'सोयाबीन',
      'cotton': 'कापूस',
      'late_blight': 'उशीरा करपा',
      'powdery_mildew': 'भुरी रोग',
      'bacterial_blight': 'जीवाणूजन्य करपा',
      'nav_community': 'फीड',
      'community_alerts': 'समुदाय अलर्ट',
      'community_subtitle': 'तुमच्या शेताजवळील रोग रिपोर्ट',
      'reports_near_you': 'तुमच्याजवळ रोग रिपोर्ट',
      'reports_nearby': 'जवळपासचे अहवाल',
      'this_week_5km': 'या आठवड्यात 5 कि.मी. मध्ये',
      'trending_diseases': 'ट्रेंडिंग रोग',
      'recent_reports': 'अलीकडील रिपोर्ट',
      'your_field': 'तुमचे शेत',
      'radius': 'परिसर',
      'ago': 'पूर्वी',
      'spray_schedule': 'फवारणी वेळापत्रक',
      'harvest_window': 'सुरक्षित कापणी ~21 दिवसांत',
      'track_recovery': 'रिकव्हरी पहा',
      'before': 'आधी',
      'after': 'नंतर',
      'drag_to_compare': 'तुलना करण्यासाठी स्लाइडर ओढा',
      'offline_mode': 'ऑफलाइन मोड',
      'scans_saved': 'स्कॅन सेव्ह झाले',
      'syncing_scans': 'ऑनलाइन — स्कॅन सिंक होत आहे...',
      'back_online': 'सर्व सिंक झाले!',
      'report_disease': 'रोग सांगा',
      'report_help_text': 'तुमच्या शेतातील रोगाची माहिती देऊन जवळच्या शेतकऱ्यांना मदत करा',
      'select_crop': 'पीक निवडा',
      'select_disease': 'रोग निवडा',
      'submit_report': 'रिपोर्ट पाठवा',
      'report_submitted': 'तुमची रिपोर्ट जवळच्या शेतकऱ्यांना पाठवली!',
      'you': 'तुम्ही',
      'wheat': 'गहू',
      'rice': 'तांदूळ',
      'leaf_curl': 'पान मुडणे',
      'root_rot': 'मूळ कुजणे',
      'voice_tap_to_speak': 'बोलण्यासाठी दाबा',
      'voice_listening': 'ऐकत आहे...',
      'voice_processing': 'समजत आहे...',
      'voice_result': 'तुम्ही म्हणालात:',
      'voice_error': 'समजले नाही, पुन्हा बोला',
      'voice_no_mic': 'माइक्रोफोनची परवानगी द्या',
      'voice_retry': 'पुन्हा प्रयत्न करा',
      'voice_close': 'बंद करा',
      'voice_followup_treatment': 'म्हणा "उपचार दाखवा"',
      'voice_followup_home': 'म्हणा "होम वर जा"',
      'voice_followup_scan': 'म्हणा "पान स्कॅन करा"',
      'voice_followup_history': 'म्हणा "इतिहास दाखवा"',
      'home_diagnostic_scan': 'डायग्नोस्टिक स्कॅन',
      'home_gallery': 'गॅलरी',
      'home_take_photo': 'फोटो काढा',
      'home_log_action': 'आजची कारवाई लॉग करा',
      'home_target_crop': 'लक्ष्य पीक',
      'home_action_type': 'कारवाई प्रकार',
      'home_quick_note': 'त्वरित नोट',
      'home_note_hint': 'उदा., 2kg NPK जोडले...',
      'home_save_log': 'लॉग सेव्ह करा',
      'home_log_saved': 'लॉग यशस्वीरित्या सेव्ह झाला!',
      'history_action_logs': 'कारवाई लॉग',
      'history_no_logs': 'अजून कोणतेही लॉग नाहीत',
      'history_no_scans': 'या हंगामात कोणतेही स्कॅन नाहीत',
      'history_season_kharif': 'खरीफ',
      'history_season_rabi': 'रबी',
      'community_helpline': 'आपातकालीन हेल्पलाइन',
      'community_helpline_kvk': 'कृषि विज्ञान केंद्र',
      'community_helpline_kvk_subtitle': 'कृषि विज्ञान केंद्र',
      'community_helpline_kcc': 'किसान कॉल सेंटर',
      'community_helpline_kcc_subtitle': 'सरकारी कृषि हेल्पलाइन (निःशुल्क)',
      'community_helpline_ppa': 'वनस्पती संरक्षण सल्लागार',
      'community_helpline_ppa_subtitle': 'जिल्हा कृषि अधिकारी',
      'community_call': 'कॉल करा',
      'treatment_baramati': 'बारामती',
      'step_done': 'झाले',
      'log_saved': 'लॉग यशस्वीरित्या सेव्ह झाला!',
      'season_kharif': 'खरीफ',
      'season_rabi': 'रबी',
      'disease_map_title': 'रोग नकाशा',
      'area_affected': 'प्रभावित क्षेत्र',
      'hide_mask': 'लपवा',
      'show_mask': 'दाखवा',
      'severity_level': 'तीव्रता पातळी',
      'analyzing_affected_area': 'प्रभावित भाग तपासत आहे...',
    },
    'kn': {
      'nav_scan': 'ಸ್ಕ್ಯಾನ್',
      'nav_result': 'ಫಲಿತಾಂಶ',
      'nav_treat': 'ಚಿಕಿತ್ಸೆ',
      'nav_history': 'ಇತಿಹಾಸ',
      'home_hint': 'ಹಾನಿಗೊಳಗಾದ ಎಲೆಯ ಕಡೆ ಕ್ಯಾಮೆರಾ ತೋರಿಸಿ',
      'home_gallery': 'ಗ್ಯಾಲರಿ',
      'home_take_photo': 'ಫೋಟೋ ತೆಗೆಯಿರಿ',
      'weather_msg': 'ಇಂದು ಆರ್ದ್ರತೆ ಹೆಚ್ಚು — ಶಿಲೀಂಧ್ರ ಅಪಾಯ',
      'disease_detected': 'ರೋಗ ಪತ್ತೆಯಾಗಿದೆ',
      'found_on': 'ಕಂಡುಬಂದಿದೆ',
      'match': 'ಹೊಂದಾಣಿಕೆ',
      'needs_attention': 'ಗಮನ ಬೇಕು',
      'critical': 'ತೀವ್ರ',
      'monitor': 'ಗಮನಿಸಿ',
      'healthy': 'ಆರೋಗ್ಯಕರ',
      'see_what_to_do': 'ಏನು ಮಾಡಬೇಕು ನೋಡಿ',
      'treatment_plan': 'ಚಿಕಿತ್ಸಾ ಯೋಜನೆ',
      'what_to_do': 'ಈಗ ಏನು ಮಾಡಬೇಕು',
      'maintenance_tips': 'ನಿರ್ವಹಣೆ ಸಲಹೆಗಳು',
      'buy_nearby': 'ಹತ್ತಿರ ಖರೀದಿಸಿ',
      'get_directions': 'ದಾರಿ ನೋಡಿ',
      'do_today': 'ಇಂದು ಮಾಡಿ',
      'ongoing': 'ಮುಂದುವರಿಸಿ',
      'step1': 'ಇಂದು ಸೂರ್ಯಾಸ್ತದ ಮೊದಲು ಮ್ಯಾಂಕೋಜೆಬ್ ಸಿಂಪಡಿಸಿ',
      'step1_detail': 'ಪ್ರತಿ ಲೀಟರ್ ನೀರಿಗೆ 2.5 ಗ್ರಾಂ ಬೆರೆಸಿ. ಎಲ್ಲಾ ಎಲೆಗಳ ಮೇಲೆ ಸಿಂಪಡಿಸಿ.',
      'step2': 'ಅತ್ಯಂತ ಹಾನಿಗೊಳಗಾದ 3-4 ಎಲೆಗಳನ್ನು ತೆಗೆಯಿರಿ',
      'step2_detail': 'ಅವುಗಳನ್ನು ಕತ್ತರಿಸಿ ಹೊಲದಿಂದ ದೂರ ತೆಗೆದುಕೊಂಡು ಹೋಗಿ.',
      'step3': 'ಬೇರಿನ ಬಳಿ ಮಾತ್ರ ನೀರು ಹಾಕಿ — ಎಲೆಗಳನ್ನು ತೊಯಿಸಬೇಡಿ',
      'step3_detail': 'ಹನಿ ನೀರಾವರಿ ಬಳಸಿ. ತೇವ ಎಲೆಗಳು ಶಿಲೀಂಧ್ರ ಬೆಳೆಯಲು ಸಹಾಯ ಮಾಡುತ್ತವೆ.',
      'crop_history': 'ಬೆಳೆ ಇತಿಹಾಸ',
      'history_subtitle': 'ನಿಮ್ಮ ಹೊಲದ ಆರೋಗ್ಯ',
      'recent_scans': 'ಇತ್ತೀಚಿನ ಸ್ಕ್ಯಾನ್‌ಗಳು',
      'scans': 'ಸ್ಕ್ಯಾನ್‌ಗಳು',
      'active': 'ಸಕ್ರಿಯ',
      'treated': 'ಚಿಕಿತ್ಸೆ',
      'diseases': 'ರೋಗಗಳು',
      'resolved': 'ಪರಿಹರಿಸಲಾಗಿದೆ',
      'status_active': 'ಸಕ್ರಿಯ',
      'status_fixed': 'ಸರಿಪಡಿಸಿದ',
      'status_ok': 'ಸರಿ',
      'field_health': 'ಹೊಲ ಆರೋಗ್ಯ',
      'watch': 'ಗಮನಿಸಿ',
      'affected': 'ಪ್ರಭಾವಿತ',
      'early_blight': 'ಆರಂಭಿಕ ಬ್ಲೈಟ್',
      'early_blight_desc': 'ಈ ಶಿಲೀಂಧ್ರ ಎಲೆಗಳ ಮೇಲೆ ವೃತ್ತಾಕಾರದ ಕಂದು ಕಲೆಗಳನ್ನು ಮಾಡುತ್ತದೆ.',
      'early_blight_spread': 'ಆರ್ದ್ರ ಹವಾಮಾನದಲ್ಲಿ ವೇಗವಾಗಿ ಹರಡುತ್ತದೆ.',
      'early_blight_urgency': '24 ಗಂಟೆಗಳಲ್ಲಿ ಕ್ರಮ ತೆಗೆದುಕೊಳ್ಳಿ.',
      'scan_details': 'ಸ್ಕ್ಯಾನ್ ವಿವರಗಳು',
      'treatment_applied': 'ಮಾಡಿದ ಚಿಕಿತ್ಸೆ',
      'no_treatment': 'ಚಿಕಿತ್ಸೆ ದಾಖಲಾಗಿಲ್ಲ',
      'view_treatment': 'ಚಿಕಿತ್ಸೆ ನೋಡಿ',
      'language': 'ಭಾಷೆ',
      'listening': 'ಕೇಳುತ್ತಿದ್ದೇನೆ...',
      'tomato': 'ಟೊಮೆಟೋ',
      'onion': 'ಈರುಳ್ಳಿ',
      'soybean': 'ಸೋಯಾಬೀನ್',
      'cotton': 'ಹತ್ತಿ',
      'late_blight': 'ತಡವಾದ ಬ್ಲೈಟ್',
      'powdery_mildew': 'ಪೌಡರಿ ಮಿಲ್ಡ್ಯೂ',
      'bacterial_blight': 'ಬ್ಯಾಕ್ಟೀರಿಯಲ್ ಬ್ಲೈಟ್',
      'nav_community': 'ಫೀಡ್',
      'community_alerts': 'ಸಮುದಾಯ ಎಚ್ಚರಿಕೆಗಳು',
      'community_subtitle': 'ನಿಮ್ಮ ಹೊಲದ ಬಳಿ ರೋಗ ವರದಿಗಳು',
      'reports_near_you': 'ನಿಮ್ಮ ಬಳಿ ರೋಗ ವರದಿಗಳು',
      'reports_nearby': 'ಹತ್ತಿರದ ವರದಿಗಳು',
      'this_week_5km': 'ಈ ವಾರ 5 ಕಿ.ಮೀ. ಒಳಗೆ',
      'trending_diseases': 'ಟ್ರೆಂಡಿಂಗ್ ರೋಗಗಳು',
      'recent_reports': 'ಇತ್ತೀಚಿನ ವರದಿಗಳು',
      'your_field': 'ನಿಮ್ಮ ಹೊಲ',
      'radius': 'ವ್ಯಾಪ್ತಿ',
      'ago': 'ಹಿಂದೆ',
      'spray_schedule': 'ಸಿಂಪಡಣೆ ವೇಳಾಪಟ್ಟಿ',
      'harvest_window': 'ಸುರಕ್ಷಿತ ಕೊಯ್ಲು ~21 ದಿನಗಳಲ್ಲಿ',
      'track_recovery': 'ಚೇತರಿಕೆ ನೋಡಿ',
      'before': 'ಮೊದಲು',
      'after': 'ನಂತರ',
      'drag_to_compare': 'ಹೋಲಿಸಲು ಸ್ಲೈಡರ್ ಎಳೆಯಿರಿ',
      'offline_mode': 'ಆಫ್‌ಲೈನ್ ಮೋಡ್',
      'scans_saved': 'ಸ್ಕ್ಯಾನ್‌ಗಳು ಉಳಿಸಲಾಗಿದೆ',
      'syncing_scans': 'ಆನ್‌ಲೈನ್ — ಸ್ಕ್ಯಾನ್‌ಗಳು ಸಿಂಕ್ ಆಗುತ್ತಿವೆ...',
      'back_online': 'ಎಲ್ಲಾ ಸಿಂಕ್ ಆಯಿತು!',
      'report_disease': 'ರೋಗ ವರದಿ ಮಾಡಿ',
      'report_help_text': 'ನಿಮ್ಮ ಹೊಲದಲ್ಲಿ ರೋಗ ವರದಿ ಮಾಡಿ ಹತ್ತಿರದ ರೈತರಿಗೆ ಸಹಾಯ ಮಾಡಿ',
      'select_crop': 'ಬೆಳೆ ಆಯ್ಕೆಮಾಡಿ',
      'select_disease': 'ರೋಗ ಆಯ್ಕೆಮಾಡಿ',
      'submit_report': 'ವರದಿ ಕಳುಹಿಸಿ',
      'report_submitted': 'ನಿಮ್ಮ ವರದಿ ಹತ್ತಿರದ ರೈತರಿಗೆ ಕಳುಹಿಸಲಾಗಿದೆ!',
      'you': 'ನೀವು',
      'wheat': 'ಗೋಧಿ',
      'rice': 'ಅಕ್ಕಿ',
      'leaf_curl': 'ಎಲೆ ಮುಲುಕು',
      'root_rot': 'ಬೇರು ಕೊಳೆ',
      'voice_tap_to_speak': 'ಮಾತನಾಡಲು ಒತ್ತಿ',
      'voice_listening': 'ಕೇಳುತ್ತಿದ್ದೇನೆ...',
      'voice_processing': 'ಅರ್ಥಮಾಡಿಕೊಳ್ಳುತ್ತಿದ್ದೇನೆ...',
      'voice_result': 'ನೀವು ಹೇಳಿದ್ದು:',
      'voice_error': 'ಅರ್ಥವಾಗಲಿಲ್ಲ, ಮತ್ತೊಮ್ಮೆ ಹೇಳಿ',
      'voice_no_mic': 'ಮೈಕ್ರೋಫೋನ್ ಅನುಮತಿ ನೀಡಿ',
      'voice_retry': 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
      'voice_close': 'ಮುಚ್ಚಿ',
      'voice_followup_treatment': '"ಚಿಕಿತ್ಸೆ ತೋರಿಸಿ" ಹೇಳಿ',
      'voice_followup_home': '"ಮುಖಪುಟಕ್ಕೆ ಹೋಗಿ" ಹೇಳಿ',
      'voice_followup_scan': '"ಎಲೆ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ" ಹೇಳಿ',
      'voice_followup_history': '"ಇತಿಹಾಸ ತೋರಿಸಿ" ಹೇಳಿ',
      'home_diagnostic_scan': 'ಡಯಾಗ್ನೋಸ್ಟಿಕ್ ಸ್ಕ್ಯಾನ್',
      'home_gallery': 'ಗ್ಯಾಲರಿ',
      'home_take_photo': 'ಫೋಟೋ ತೆಗೆಯಿರಿ',
      'home_log_action': 'ಇಂದಿನ ಕಾರ್ಯವನ್ನು ದಾಖಲಿಸಿ',
      'home_target_crop': 'ಗುರಿ ಬೆಳೆ',
      'home_action_type': 'ಕ್ರಿಯೆಯ ಪ್ರಕಾರ',
      'home_quick_note': 'ತ್ವರಿತ ಟಿಪ್ಪಣಿ',
      'home_note_hint': 'ಉದಾ., 2kg NPK ಸೇರಿಸಲಾಗಿದೆ...',
      'home_save_log': 'ಲಾಗ್ ಉಳಿಸಿ',
      'home_log_saved': 'ಲಾಗ್ ಯಶಸ್ವಿಯಾಗಿ ಉಳಿಸಲಾಯಿತು!',
      'history_action_logs': 'ಕ್ರಿಯೆ ಲಾಗ್‌ಗಳು',
      'history_no_logs': 'ಇನ್ನೂ ಯಾವುದೇ ಲಾಗ್‌ಗಳಿಲ್ಲ',
      'history_no_scans': 'ಈ ಋತುವಿನಲ್ಲಿ ಯಾವುದೇ ಸ್ಕ್ಯಾನ್‌ಗಳಿಲ್ಲ',
      'history_season_kharif': 'ಖಾರಿಫ್',
      'history_season_rabi': 'ರಬಿ',
      'community_helpline': 'ತುರ್ತು ಸಹಾಯವಾಣಿ',
      'community_helpline_kvk': 'ಕೃಷಿ ವಿಜ್ಞಾನ ಕೇಂದ್ರ',
      'community_helpline_kvk_subtitle': 'ಕೃಷಿ ವಿಜ್ಞಾನ ಕೇಂದ್ರ',
      'community_helpline_kcc': 'ಕಿಸಾನ್ ಕಾಲ್ ಸೆಂಟರ್',
      'community_helpline_kcc_subtitle': 'ಸರ್ಕಾರಿ ಕೃಷಿ ಸಹಾಯವಾಣಿ (ಉಚಿತ)',
      'community_helpline_ppa': 'ಸಸ್ಯ ಸಂರಕ್ಷಣಾ ಸಲಹೆಗಾರ',
      'community_helpline_ppa_subtitle': 'ಜಿಲ್ಲಾ ಕೃಷಿ ಅಧಿಕಾರಿ',
      'community_call': 'ಕರೆ ಮಾಡಿ',
      'treatment_baramati': 'ಬಾರಾಮತಿ',
      'step_done': 'ಮುಗಿದಿದೆ',
      'log_saved': 'ಲಾಗ್ ಯಶಸ್ವಿಯಾಗಿ ಉಳಿಸಲಾಯಿತು!',
      'season_kharif': 'ಖಾರಿಫ್',
      'season_rabi': 'ರಬಿ',
      'disease_map_title': 'ರೋಗ ನಕ್ಷೆ',
      'area_affected': 'ಪ್ರಭಾವಿತ ಪ್ರದೇಶ',
      'hide_mask': 'ಮರೆಮಾಡಿ',
      'show_mask': 'ತೋರಿಸಿ',
      'severity_level': 'ತೀವ್ರತೆ ಮಟ್ಟ',
      'analyzing_affected_area': 'ಪ್ರಭಾವಿತ ಪ್ರದೇಶ ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...',
    },
    'te': {
      'nav_scan': 'స్కాన్',
      'nav_result': 'ఫలితం',
      'nav_treat': 'చికిత్స',
      'nav_history': 'చరిత్ర',
      'home_hint': 'ప్రభావిత ఆకును చూపండి',
      'home_gallery': 'గ్యాలరీ',
      'home_take_photo': 'ఫోటో తీయండి',
      'weather_msg': 'ఈరోజు తేమ ఎక్కువ — ఫంగస్ ప్రమాదం',
      'disease_detected': 'వ్యాధి కనుగొనబడింది',
      'found_on': 'కనుగొనబడింది',
      'match': 'మ్యాచ్',
      'needs_attention': 'శ్రద్ధ అవసరం',
      'critical': 'తీవ్రమైన',
      'monitor': 'గమనించండి',
      'healthy': 'ఆరోగ్యం',
      'see_what_to_do': 'ఏమి చేయాలో చూడండి',
      'treatment_plan': 'చికిత్స ప్రణాళిక',
      'what_to_do': 'ఇప్పుడు ఏమి చేయాలి',
      'maintenance_tips': 'నిర్వహణ చిట్కాలు',
      'buy_nearby': 'సమీపంలో కొనండి',
      'get_directions': 'దారి చూడండి',
      'do_today': 'ఈరోజు చేయండి',
      'ongoing': 'కొనసాగించండి',
      'step1': 'ఈరోజు సూర్యాస్తమయానికి ముందు మాంకోజెబ్ పిచికారీ చేయండి',
      'step1_detail': 'లీటరు నీటికి 2.5 గ్రా కలపండి. అన్ని ఆకులపై పిచికారీ చేయండి.',
      'step2': 'ఎక్కువగా ప్రభావితమైన 3-4 ఆకులను తొలగించండి',
      'step2_detail': 'వాటిని కత్తిరించి పొలం నుండి దూరంగా తీసుకెళ్ళండి.',
      'step3': 'మొదలు వద్ద మాత్రమే నీరు పోయండి — ఆకులను తడపకండి',
      'step3_detail': 'డ్రిప్ ఇరిగేషన్ వాడండి. తడి ఆకులు ఫంగస్ పెరగడానికి సహాయపడతాయి.',
      'crop_history': 'పంట చరిత్ర',
      'history_subtitle': 'మీ పొలం ఆరోగ్యం',
      'recent_scans': 'ఇటీవలి స్కాన్లు',
      'scans': 'స్కాన్లు',
      'active': 'సక్రియం',
      'treated': 'చికిత్స',
      'diseases': 'వ్యాధులు',
      'resolved': 'పరిష్కరించబడింది',
      'status_active': 'సక్రియం',
      'status_fixed': 'సరిచేశారు',
      'status_ok': 'సరే',
      'field_health': 'పొలం ఆరోగ్యం',
      'watch': 'గమనించండి',
      'affected': 'ప్రభావితం',
      'early_blight': 'ఎర్లీ బ్లైట్',
      'early_blight_desc': 'ఈ ఫంగస్ ఆకులపై గుండ్రని గోధుమ మచ్చలు చేస్తుంది.',
      'early_blight_spread': 'తేమ వాతావరణంలో వేగంగా వ్యాపిస్తుంది.',
      'early_blight_urgency': '24 గంటల్లో చర్య తీసుకోండి.',
      'scan_details': 'స్కాన్ వివరాలు',
      'treatment_applied': 'చేసిన చికిత్స',
      'no_treatment': 'చికిత్స నమోదు కాలేదు',
      'view_treatment': 'చికిత్స చూడండి',
      'language': 'భాష',
      'listening': 'వింటున్నాము...',
      'tomato': 'టమాటా',
      'onion': 'ఉల్లిపాయ',
      'soybean': 'సోయాబీన్',
      'cotton': 'పత్తి',
      'late_blight': 'లేట్ బ్లైట్',
      'powdery_mildew': 'పౌడరీ మిల్డ్యూ',
      'bacterial_blight': 'బ్యాక్టీరియల్ బ్లైట్',
      'nav_community': 'ఫీడ్',
      'community_alerts': 'సమాజ హెచ్చరికలు',
      'community_subtitle': 'మీ పొలం సమీపంలో వ్యాధి నివేదికలు',
      'reports_near_you': 'మీకు సమీపంలో వ్యాధి నివేదికలు',
      'reports_nearby': 'సమీపంలోని నివేదికలు',
      'this_week_5km': 'ఈ వారం 5 కి.మీ. లోపల',
      'trending_diseases': 'ట్రెండింగ్ వ్యాధులు',
      'recent_reports': 'ఇటీవలి నివేదికలు',
      'your_field': 'మీ పొలం',
      'radius': 'వ్యాసార్ధం',
      'ago': 'క్రితం',
      'spray_schedule': 'పిచికారీ షెడ్యూల్',
      'harvest_window': 'సురక్షిత పంట కోత ~21 రోజుల్లో',
      'track_recovery': 'రికవరీ చూడండి',
      'before': 'ముందు',
      'after': 'తరువాత',
      'drag_to_compare': 'పోల్చడానికి స్లైడర్ లాగండి',
      'offline_mode': 'ఆఫ్‌లైన్ మోడ్',
      'scans_saved': 'స్కాన్లు సేవ్ చేయబడ్డాయి',
      'syncing_scans': 'ఆన్‌లైన్ — స్కాన్లు సింక్ అవుతున్నాయి...',
      'back_online': 'అన్నీ సింక్ అయ్యాయి!',
      'report_disease': 'వ్యాధి నివేదించండి',
      'report_help_text': 'మీ పొలంలో వ్యాధిని నివేదించి సమీపంలోని రైతులకు సహాయం చేయండి',
      'select_crop': 'పంట ఎంచుకోండి',
      'select_disease': 'వ్యాధి ఎంచుకోండి',
      'submit_report': 'నివేదిక పంపండి',
      'report_submitted': 'మీ నివేదిక సమీపంలోని రైతులకు పంపబడింది!',
      'you': 'మీరు',
      'wheat': 'గోధుమ',
      'rice': 'వరి',
      'leaf_curl': 'ఆకు ముడత',
      'root_rot': 'వేరు కుళ్ళు',
      'voice_tap_to_speak': 'మాట్లాడడానికి నొక్కండి',
      'voice_listening': 'వింటున్నాము...',
      'voice_processing': 'అర్థం చేసుకుంటున్నాము...',
      'voice_result': 'మీరు చెప్పింది:',
      'voice_error': 'అర్థం కాలేదు, మళ్లీ చెప్పండి',
      'voice_no_mic': 'మైక్రోఫోన్ అనుమతి ఇవ్వండి',
      'voice_retry': 'మళ్లీ ప్రయత్నించండి',
      'voice_close': 'మూసివేయి',
      'voice_followup_treatment': '"చికిత్స చూపించు" అనండి',
      'voice_followup_home': '"హోమ్ కు వెళ్ళు" అనండి',
      'voice_followup_scan': '"ఆకు స్కాన్ చేయి" అనండి',
      'voice_followup_history': '"చరిత్ర చూపించు" అనండి',
      'home_diagnostic_scan': 'డయగ్నోస్టిక్ స్కాన్',
      'home_gallery': 'గ్యాలరీ',
      'home_take_photo': 'ఫోటో తీయండి',
      'home_log_action': 'నేటి చర్యను నమోదు చేయండి',
      'home_target_crop': 'లక్ష్యం పంట',
      'home_action_type': 'చర్య రకం',
      'home_quick_note': 'త్వరిత గమనిక',
      'home_note_hint': 'ఉదా., 2kg NPK జోడించబడింది...',
      'home_save_log': 'లాగ్ సేవ్ చేయి',
      'home_log_saved': 'లాగ్ విజయవంతంగా సేవ్ అయ్యింది!',
      'history_action_logs': 'చర్య లాగ్‌లు',
      'history_no_logs': 'ఇంకా ఎటువంటి లాగ్‌లు లేవు',
      'history_no_scans': 'ఈ సీజన్‌లో ఎటువంటి స్కాన్‌లు లేవు',
      'history_season_kharif': 'ఖరీఫ్',
      'history_season_rabi': 'రబి',
      'community_helpline': 'అత్యవసర హెల్ప్‌లైన్',
      'community_helpline_kvk': 'కృషి విజ్ఞాన్ కేంద్రం',
      'community_helpline_kvk_subtitle': 'వ్యవసాయ శాస్త్ర కేంద్రం',
      'community_helpline_kcc': 'కిసాన్ కాల్ సెంటర్',
      'community_helpline_kcc_subtitle': 'ప్రభుత్వ వ్యవసాయ హెల్ప్‌లైన్ (ఉచితం)',
      'community_helpline_ppa': 'మొక్క రక్షణ సలహాదారు',
      'community_helpline_ppa_subtitle': 'జిల్లా వ్యవసాయ అధికారి',
      'community_call': 'కాల్ చేయండి',
      'treatment_baramati': 'బారామతి',
      'step_done': 'పూర్తయింది',
      'log_saved': 'లాగ్ విజయవంతంగా సేవ్ అయ్యింది!',
      'season_kharif': 'ఖరీఫ్',
      'season_rabi': 'రబి',
      'disease_map_title': 'వ్యాధి మ్యాప్',
      'area_affected': 'ప్రభావిత ప్రాంతం',
      'hide_mask': 'దాచు',
      'show_mask': 'చూపించు',
      'severity_level': 'తీవ్రత స్థాయి',
      'analyzing_affected_area': 'ప్రభావిత ప్రాంతాన్ని విశ్లేషిస్తోంది...',
    },
    'ta': {
      'nav_scan': 'ஸ்கேன்',
      'nav_result': 'முடிவு',
      'nav_treat': 'சிகிச்சை',
      'nav_history': 'வரலாறு',
      'home_hint': 'பாதிக்கப்பட்ட இலையை காட்டுங்கள்',
      'home_gallery': 'கேலரி',
      'home_take_photo': 'புகைப்படம் எடு',
      'weather_msg': 'இன்று ஈரப்பதம் அதிகம் — பூஞ்சை ஆபத்து',
      'disease_detected': 'நோய் கண்டறியப்பட்டது',
      'found_on': 'கண்டறியப்பட்டது',
      'match': 'பொருத்தம்',
      'needs_attention': 'கவனம் தேவை',
      'critical': 'தீவிரமான',
      'monitor': 'கவனி',
      'healthy': 'ஆரோக்கியம்',
      'see_what_to_do': 'என்ன செய்ய வேண்டும்',
      'treatment_plan': 'சிகிச்சை திட்டம்',
      'what_to_do': 'இப்போது என்ன செய்ய வேண்டும்',
      'maintenance_tips': 'பராமரிப்பு குறிப்புகள்',
      'buy_nearby': 'அருகில் வாங்கவும்',
      'get_directions': 'வழி காட்டு',
      'do_today': 'இன்று செய்',
      'ongoing': 'தொடர்ச்சி',
      'step1': 'இன்று சூரிய அஸ்தமனத்திற்கு முன் மான்கோசெப் தெளிக்கவும்',
      'step1_detail': 'ஒரு லிட்டர் நீரில் 2.5 கிராம் கலக்கவும்.',
      'step2': 'மிகவும் பாதிக்கப்பட்ட 3-4 இலைகளை நீக்கவும்',
      'step2_detail': 'வெட்டி வயலில் இருந்து எடுத்துச் செல்லுங்கள்.',
      'step3': 'அடிப்பகுதியில் மட்டும் நீர் ஊற்றவும்',
      'step3_detail': 'சொட்டு நீர் பாசனம் பயன்படுத்தவும்.',
      'crop_history': 'பயிர் வரலாறு',
      'history_subtitle': 'உங்கள் வயல் ஆரோக்கியம்',
      'recent_scans': 'சமீபத்திய ஸ்கேன்கள்',
      'scans': 'ஸ்கேன்கள்',
      'active': 'செயலில்',
      'treated': 'சிகிச்சை',
      'diseases': 'நோய்கள்',
      'resolved': 'தீர்க்கப்பட்டது',
      'status_active': 'செயலில்',
      'status_fixed': 'சரி',
      'status_ok': 'சரி',
      'field_health': 'வயல் ஆரோக்கியம்',
      'watch': 'கவனி',
      'affected': 'பாதிக்கப்பட்ட',
      'early_blight': 'ஆரம்ப கருகல்',
      'early_blight_desc': 'இந்த பூஞ்சை இலைகளில் வட்ட பழுப்பு புள்ளிகளை உருவாக்குகிறது.',
      'early_blight_spread': 'ஈரப்பதமான வானிலையில் வேகமாக பரவுகிறது.',
      'early_blight_urgency': '24 மணி நேரத்தில் நடவடிக்கை எடுக்கவும்.',
      'scan_details': 'ஸ்கேன் விவரங்கள்',
      'treatment_applied': 'செய்த சிகிச்சை',
      'no_treatment': 'சிகிச்சை பதிவு இல்லை',
      'view_treatment': 'சிகிச்சை பார்க்க',
      'language': 'மொழி',
      'listening': 'கேட்கிறது...',
      'tomato': 'தக்காளி',
      'onion': 'வெங்காயம்',
      'soybean': 'சோயாபீன்',
      'cotton': 'பருத்தி',
      'late_blight': 'லேட் பிளைட்',
      'powdery_mildew': 'பவுடரி மில்டியூ',
      'bacterial_blight': 'பாக்டீரியல் பிளைட்',
      'nav_community': 'ஊட்டம்',
      'community_alerts': 'சமூக எச்சரிக்கைகள்',
      'community_subtitle': 'உங்கள் பண்ணை அருகில் நோய் அறிக்கைகள்',
      'reports_near_you': 'உங்களுக்கு அருகில் நோய் அறிக்கைகள்',
      'reports_nearby': 'அருகிலுள்ள அறிக்கைகள்',
      'this_week_5km': 'இந்த வாரம் 5 கி.மீ. க்குள்',
      'trending_diseases': 'நோய் போக்குகள்',
      'recent_reports': 'சமீபத்திய அறிக்கைகள்',
      'your_field': 'உங்கள் வயல்',
      'radius': 'ஆரை',
      'ago': 'முன்',
      'spray_schedule': 'தெளிப்பு அட்டவணை',
      'harvest_window': 'பாதுகாப்பான அறுவடை ~21 நாட்களில்',
      'track_recovery': 'மீட்பு பார்க்க',
      'before': 'முன்',
      'after': 'பின்',
      'drag_to_compare': 'ஒப்பிட்டு பார்க்க ஸ்லைடரை இழுக்கவும்',
      'offline_mode': 'ஆஃப்லைன் பயன்முறை',
      'scans_saved': 'ஸ்கேன்கள் சேமிக்கப்பட்டன',
      'syncing_scans': 'ஆன்லைன் — ஸ்கேன்கள் ஒத்திசைக்கப்படுகின்றன...',
      'back_online': 'அனைத்தும் ஒத்திசைவு ஆனது!',
      'report_disease': 'நோய் புகாரளி',
      'report_help_text': 'உங்கள் வயலில் நோயை புகாரளித்து அருகிலுள்ள விவசாயிகளுக்கு உதவுங்கள்',
      'select_crop': 'பயிர் தேர்ந்தெடு',
      'select_disease': 'நோய் தேர்ந்தெடு',
      'submit_report': 'புகார் அனுப்பு',
      'report_submitted': 'உங்கள் புகார் அருகிலுள்ள விவசாயிகளுக்கு அனுப்பப்பட்டது!',
      'you': 'நீங்கள்',
      'wheat': 'கோதுமை',
      'rice': 'அரிசி',
      'leaf_curl': 'இலை சுருட்டை',
      'root_rot': 'வேர் அழுகல்',
      'voice_tap_to_speak': 'பேச கிளிக் செய்யவும்',
      'voice_listening': 'கேட்கிறது...',
      'voice_processing': 'புரிகிறது...',
      'voice_result': 'நீங்கள் சொன்னது:',
      'voice_error': 'புரியவில்லை, மீண்டும் சொல்லவும்',
      'voice_no_mic': 'மைக்ரோஃபோன் அனுமதி அளிக்கவும்',
      'voice_retry': 'மீண்டும் முயற்சிக்கவும்',
      'voice_close': 'மூடு',
      'voice_followup_treatment': '"சிகிச்சை காட்டு" சொல்லவும்',
      'voice_followup_home': '"முகப்புக்கு செல்" சொல்லவும்',
      'voice_followup_scan': '"இலை ஸ்கேன் செய்" சொல்லவும்',
      'voice_followup_history': '"வரலாறு காட்டு" சொல்லவும்',
      'home_diagnostic_scan': 'டயக்னோஸ்டிக் ஸ்கேன்',
      'home_gallery': 'கேலரி',
      'home_take_photo': 'புகைப்படம் எடு',
      'home_log_action': 'இன்றைய செயலை பதிவு செய்',
      'home_target_crop': 'இலக்கு பயிர்',
      'home_action_type': 'செயல் வகை',
      'home_quick_note': 'விரைவான குறிப்பு',
      'home_note_hint': 'எ.கா., 2kg NPK சேர்க்கப்பட்டது...',
      'home_save_log': 'லாக் சேமி',
      'home_log_saved': 'லாக் வெற்றிகரமாக சேமிக்கப்பட்டது!',
      'history_action_logs': 'செயல் லாக்குகள்',
      'history_no_logs': 'இன்னும் லாக்குகள் இல்லை',
      'history_no_scans': 'இந்த பருவத்தில் ஸ்கேன்கள் இல்லை',
      'history_season_kharif': 'காரீஃப்',
      'history_season_rabi': 'ரபி',
      'community_helpline': 'அவசர உதவி எண்',
      'community_helpline_kvk': 'கிருஷி விக்யான் கேந்திரா',
      'community_helpline_kvk_subtitle': 'வேளாண் அறிவியல் மையம்',
      'community_helpline_kcc': 'கிசான் கால் சென்டர்',
      'community_helpline_kcc_subtitle': 'அரசு வேளாண் உதவி எண் (இலவசம்)',
      'community_helpline_ppa': 'பயிர் பாதுகாப்பு ஆலோசகர்',
      'community_helpline_ppa_subtitle': 'மாவட்ட வேளாண் அலுவலர்',
      'community_call': 'அழை',
      'treatment_baramati': 'பாராமதி',
      'step_done': 'முடிந்தது',
      'log_saved': 'லாக் வெற்றிகரமாக சேமிக்கப்பட்டது!',
      'season_kharif': 'காரீஃப்',
      'season_rabi': 'ரபி',
      'disease_map_title': 'நோய் வரைபடம்',
      'area_affected': 'பாதிக்கப்பட்ட பகுதி',
      'hide_mask': 'மறை',
      'show_mask': 'காட்டு',
      'severity_level': 'தீவிர நிலை',
      'analyzing_affected_area': 'பாதிக்கப்பட்ட பகுதியை ஆராய்கிறது...',
    },
  };
}
