import 'package:flutter/material.dart';

class LanguageScope extends InheritedWidget {
  final String language;
  final ValueChanged<String> onLanguageChanged;

  const LanguageScope({
    super.key,
    required this.language,
    required this.onLanguageChanged,
    required super.child,
  });

  static LanguageScope? of(BuildContext context) {
    return context.dependOnInheritedWidgetOfExactType<LanguageScope>();
  }

  @override
  bool updateShouldNotify(LanguageScope old) => old.language != language;
}

String t(BuildContext context, String key) {
  final lang = LanguageScope.of(context)?.language ?? 'en';
  return AppTranslations.get(lang, key);
}

class SupportedLanguage {
  final String code;
  final String name;
  final String nativeName;
  final String ttsLocale;

  const SupportedLanguage({
    required this.code,
    required this.name,
    required this.nativeName,
    required this.ttsLocale,
  });
}

const List<SupportedLanguage> supportedLanguages = [
  SupportedLanguage(code: 'en', name: 'English', nativeName: 'English', ttsLocale: 'en-IN'),
  SupportedLanguage(code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', ttsLocale: 'hi-IN'),
  SupportedLanguage(code: 'mr', name: 'Marathi', nativeName: 'मराठी', ttsLocale: 'mr-IN'),
  SupportedLanguage(code: 'te', name: 'Telugu', nativeName: 'తెలుగు', ttsLocale: 'te-IN'),
  SupportedLanguage(code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', ttsLocale: 'ta-IN'),
];

class AppTranslations {
  AppTranslations._();

  static String get(String lang, String key) {
    return _translations[lang]?[key] ?? _translations['en']?[key] ?? key;
  }

  static final Map<String, Map<String, String>> _translations = {
    'en': {
      'nav_scan': 'Scan',
      'nav_result': 'Result',
      'nav_treat': 'Treat',
      'nav_history': 'History',
      'home_hint': 'Point at the affected leaf',
      'home_gallery': 'Gallery',
      'home_take_photo': 'Take Photo',
      'weather_msg': 'High humidity today — risk of fungus',
      'disease_detected': 'Disease Detected',
      'found_on': 'Found on',
      'match': 'match',
      'needs_attention': 'Needs Attention',
      'critical': 'Critical',
      'monitor': 'Monitor',
      'healthy': 'Healthy',
      'see_what_to_do': 'See What To Do',
      'treatment_plan': 'Treatment Plan',
      'what_to_do': 'What to do now',
      'maintenance_tips': 'Maintenance Tips',
      'buy_nearby': 'Buy nearby',
      'get_directions': 'Get Directions',
      'do_today': 'Do today',
      'ongoing': 'Ongoing',
      'step1': 'Spray Mancozeb solution before sunset today',
      'step1_detail': 'Mix 2.5g per litre of water. Spray on all leaves, top and bottom.',
      'step2': 'Remove the 3-4 most affected leaves',
      'step2_detail': 'Cut them off and take them away from the field. Don\'t leave them on the ground.',
      'step3': 'Water at the base only — avoid wetting leaves',
      'step3_detail': 'Use drip irrigation or pour water directly at the roots. Wet leaves help the fungus grow.',
      'crop_history': 'Crop History',
      'history_subtitle': 'Your field health over time',
      'recent_scans': 'Recent Scans',
      'scans': 'Scans',
      'diseases': 'Diseases',
      'resolved': 'Resolved',
      'status_active': 'Active',
      'status_fixed': 'Fixed',
      'status_ok': 'OK',
      'field_health': 'Field Health',
      'watch': 'Watch',
      'affected': 'Affected',
      'early_blight': 'Early Blight',
      'early_blight_sci': 'Alternaria solani',
      'early_blight_desc': 'This fungus makes round brown spots with rings on the leaves. It starts on the older leaves at the bottom and spreads upward.',
      'early_blight_spread': 'Spreads fast in humid weather, especially when leaves stay wet overnight.',
      'early_blight_urgency': 'Act within 24 hours — this spreads quickly in wet conditions.',
      'confidence': 'Confidence',
      'scan_details': 'Scan Details',
      'treatment_applied': 'Treatment Applied',
      'no_treatment': 'No treatment recorded',
      'view_treatment': 'View Treatment',
      'language': 'Language',
      'listening': 'Listening...',
      'tomato': 'Tomato',
      'onion': 'Onion',
      'soybean': 'Soybean',
      'cotton': 'Cotton',
      'late_blight': 'Late Blight',
      'powdery_mildew': 'Powdery Mildew',
      'bacterial_blight': 'Bacterial Blight',
      'nav_community': 'Feed',
      'community_alerts': 'Community Alerts',
      'community_subtitle': 'Disease reports near your farm',
      'reports_near_you': 'Disease reports near you',
      'this_week_5km': 'This week within 5 km',
      'trending_diseases': 'Trending Diseases',
      'recent_reports': 'Recent Reports',
      'your_field': 'Your Field',
      'radius': 'radius',
      'ago': 'ago',
      'spray_schedule': 'Spray Schedule',
      'harvest_window': 'Safe harvest window opens in ~21 days',
      'track_recovery': 'Track Recovery',
      'before': 'Before',
      'after': 'After',
      'drag_to_compare': 'Drag the slider to compare before and after',
      'offline_mode': 'Offline mode',
      'scans_saved': 'scans saved locally',
      'syncing_scans': 'Back online — syncing scans...',
      'back_online': 'All synced!',
      'report_disease': 'Report Disease',
      'report_help_text': 'Help nearby farmers by reporting diseases in your field',
      'select_crop': 'Select Crop',
      'select_disease': 'Select Disease',
      'submit_report': 'Submit Report',
      'report_submitted': 'Your report has been shared with nearby farmers!',
      'you': 'You',
      'wheat': 'Wheat',
      'rice': 'Rice',
      'leaf_curl': 'Leaf Curl',
      'root_rot': 'Root Rot',
    },
    'hi': {
      'nav_scan': 'स्कैन',
      'nav_result': 'नतीजा',
      'nav_treat': 'इलाज',
      'nav_history': 'इतिहास',
      'home_hint': 'प्रभावित पत्ते की ओर कैमरा करें',
      'home_gallery': 'गैलरी',
      'home_take_photo': 'फोटो लें',
      'weather_msg': 'आज नमी ज़्यादा है — फफूंद का खतरा',
      'disease_detected': 'रोग पाया गया',
      'found_on': 'पाया गया',
      'match': 'मैच',
      'needs_attention': 'ध्यान दें',
      'critical': 'गंभीर',
      'monitor': 'निगरानी',
      'healthy': 'स्वस्थ',
      'see_what_to_do': 'क्या करें देखें',
      'treatment_plan': 'इलाज योजना',
      'what_to_do': 'अभी क्या करें',
      'maintenance_tips': 'रखरखाव सुझाव',
      'buy_nearby': 'पास में खरीदें',
      'get_directions': 'रास्ता देखें',
      'do_today': 'आज करें',
      'ongoing': 'जारी रखें',
      'step1': 'आज सूरज डूबने से पहले मैन्कोज़ेब का घोल छिड़कें',
      'step1_detail': '2.5 ग्राम प्रति लीटर पानी में मिलाएं। सभी पत्तों पर ऊपर-नीचे छिड़कें।',
      'step2': 'सबसे ज़्यादा प्रभावित 3-4 पत्ते तोड़ दें',
      'step2_detail': 'उन्हें काटकर खेत से दूर ले जाएं। ज़मीन पर न छोड़ें।',
      'step3': 'सिर्फ जड़ में पानी दें — पत्तों को गीला न करें',
      'step3_detail': 'ड्रिप सिंचाई का उपयोग करें। गीले पत्ते फफूंद बढ़ाते हैं।',
      'crop_history': 'फसल इतिहास',
      'history_subtitle': 'आपके खेत की सेहत',
      'recent_scans': 'हाल के स्कैन',
      'scans': 'स्कैन',
      'diseases': 'रोग',
      'resolved': 'ठीक हुआ',
      'status_active': 'सक्रिय',
      'status_fixed': 'ठीक',
      'status_ok': 'ठीक',
      'field_health': 'खेत स्वास्थ्य',
      'watch': 'नज़र रखें',
      'affected': 'प्रभावित',
      'early_blight': 'अगेती झुलसा',
      'early_blight_sci': 'Alternaria solani',
      'early_blight_desc': 'यह फफूंद पत्तों पर गोल भूरे धब्बे बनाती है। यह नीचे के पुराने पत्तों से शुरू होकर ऊपर फैलती है।',
      'early_blight_spread': 'गीले मौसम में तेज़ी से फैलती है, खासकर जब पत्ते रात भर गीले रहें।',
      'early_blight_urgency': '24 घंटे में इलाज करें — गीले मौसम में तेज़ी से फैलता है।',
      'confidence': 'विश्वसनीयता',
      'scan_details': 'स्कैन विवरण',
      'treatment_applied': 'उपचार किया गया',
      'no_treatment': 'कोई उपचार दर्ज नहीं',
      'view_treatment': 'उपचार देखें',
      'language': 'भाषा',
      'listening': 'सुन रहे हैं...',
      'tomato': 'टमाटर',
      'onion': 'प्याज',
      'soybean': 'सोयाबीन',
      'cotton': 'कपास',
      'late_blight': 'पछेती झुलसा',
      'powdery_mildew': 'चूर्णी फफूंद',
      'bacterial_blight': 'जीवाणु झुलसा',
      'nav_community': 'फीड',
      'community_alerts': 'समुदाय अलर्ट',
      'community_subtitle': 'आपके खेत के पास रोग रिपोर्ट',
      'reports_near_you': 'आपके पास रोग रिपोर्ट',
      'this_week_5km': 'इस हफ्ते 5 कि.मी. के अंदर',
      'trending_diseases': 'चलन में रोग',
      'recent_reports': 'हाल की रिपोर्ट',
      'your_field': 'आपका खेत',
      'radius': 'दायरा',
      'ago': 'पहले',
      'spray_schedule': 'छिड़काव कार्यक्रम',
      'harvest_window': 'सुरक्षित कटाई ~21 दिन में',
      'track_recovery': 'रिकवरी देखें',
      'before': 'पहले',
      'after': 'बाद में',
      'drag_to_compare': 'तुलना के लिए स्लाइडर खींचें',
      'offline_mode': 'ऑफलाइन मोड',
      'scans_saved': 'स्कैन सेव हैं',
      'syncing_scans': 'ऑनलाइन — स्कैन सिंक हो रहे हैं...',
      'back_online': 'सब सिंक हो गया!',
      'report_disease': 'रोग रिपोर्ट करें',
      'report_help_text': 'अपने खेत में रोग की रिपोर्ट करके पास के किसानों की मदद करें',
      'select_crop': 'फसल चुनें',
      'select_disease': 'रोग चुनें',
      'submit_report': 'रिपोर्ट भेजें',
      'report_submitted': 'आपकी रिपोर्ट पास के किसानों को भेजी गई!',
      'you': 'आप',
      'wheat': 'गेहूं',
      'rice': 'चावल',
      'leaf_curl': 'पत्ता मुड़ना',
      'root_rot': 'जड़ सड़न',
    },
    'mr': {
      'nav_scan': 'स्कॅन',
      'nav_result': 'निकाल',
      'nav_treat': 'उपचार',
      'nav_history': 'इतिहास',
      'home_hint': 'प्रभावित पानाकडे कॅमेरा करा',
      'home_gallery': 'गॅलरी',
      'home_take_photo': 'फोटो काढा',
      'weather_msg': 'आज हवेत ओलावा जास्त — बुरशीचा धोका',
      'disease_detected': 'रोग आढळला',
      'found_on': 'आढळले',
      'match': 'जुळणी',
      'needs_attention': 'लक्ष द्या',
      'critical': 'गंभीर',
      'monitor': 'लक्ष ठेवा',
      'healthy': 'निरोगी',
      'see_what_to_do': 'काय करावे ते पहा',
      'treatment_plan': 'उपचार योजना',
      'what_to_do': 'आत्ता काय करावे',
      'maintenance_tips': 'देखभाल टिप्स',
      'buy_nearby': 'जवळपास खरेदी करा',
      'get_directions': 'मार्ग दाखवा',
      'do_today': 'आज करा',
      'ongoing': 'चालू ठेवा',
      'step1': 'आज सूर्यास्तापूर्वी मॅन्कोझेब फवारणी करा',
      'step1_detail': '2.5 ग्रॅम प्रति लिटर पाण्यात मिसळा. सर्व पानांवर वर-खाली फवारा.',
      'step2': 'सर्वात जास्त प्रभावित 3-4 पाने काढून टाका',
      'step2_detail': 'ती कापून शेतापासून दूर न्या. जमिनीवर सोडू नका.',
      'step3': 'फक्त मुळाशी पाणी द्या — पाने ओले करू नका',
      'step3_detail': 'ठिबक सिंचन वापरा. ओले पाने बुरशी वाढवतात.',
      'crop_history': 'पीक इतिहास',
      'history_subtitle': 'तुमच्या शेताचे आरोग्य',
      'recent_scans': 'अलीकडील स्कॅन',
      'scans': 'स्कॅन',
      'diseases': 'रोग',
      'resolved': 'निराकरण',
      'status_active': 'सक्रिय',
      'status_fixed': 'दुरुस्त',
      'status_ok': 'ठीक',
      'field_health': 'शेत आरोग्य',
      'watch': 'लक्ष ठेवा',
      'affected': 'प्रभावित',
      'early_blight': 'लवकर करपा',
      'early_blight_sci': 'Alternaria solani',
      'early_blight_desc': 'हा बुरशीजन्य रोग पानांवर गोलाकार तपकिरी डाग बनवतो. तो खालच्या जुन्या पानांपासून सुरू होतो.',
      'early_blight_spread': 'ओलसर हवामानात वेगाने पसरतो, विशेषतः पाने रात्रभर ओली राहिल्यास.',
      'early_blight_urgency': '24 तासांत उपचार करा — ओलसर हवामानात वेगाने पसरतो.',
      'confidence': 'विश्वासार्हता',
      'scan_details': 'स्कॅन तपशील',
      'treatment_applied': 'केलेला उपचार',
      'no_treatment': 'उपचार नोंदलेला नाही',
      'view_treatment': 'उपचार पहा',
      'language': 'भाषा',
      'listening': 'ऐकत आहे...',
      'tomato': 'टोमॅटो',
      'onion': 'कांदा',
      'soybean': 'सोयाबीन',
      'cotton': 'कापूस',
      'late_blight': 'उशीरा करपा',
      'powdery_mildew': 'भुरी रोग',
      'bacterial_blight': 'जीवाणूजन्य करपा',
      'nav_community': 'फीड',
      'community_alerts': 'समुदाय अलर्ट',
      'community_subtitle': 'तुमच्या शेताजवळील रोग रिपोर्ट',
      'reports_near_you': 'तुमच्याजवळ रोग रिपोर्ट',
      'this_week_5km': 'या आठवड्यात 5 कि.मी. मध्ये',
      'trending_diseases': 'ट्रेंडिंग रोग',
      'recent_reports': 'अलीकडील रिपोर्ट',
      'your_field': 'तुमचे शेत',
      'radius': 'परिसर',
      'ago': 'पूर्वी',
      'spray_schedule': 'फवारणी वेळापत्रक',
      'harvest_window': 'सुरक्षित कापणी ~21 दिवसांत',
      'track_recovery': 'रिकव्हरी पहा',
      'before': 'आधी',
      'after': 'नंतर',
      'drag_to_compare': 'तुलना करण्यासाठी स्लाइडर ओढा',
      'offline_mode': 'ऑफलाइन मोड',
      'scans_saved': 'स्कॅन सेव्ह झाले',
      'syncing_scans': 'ऑनलाइन — स्कॅन सिंक होत आहे...',
      'back_online': 'सर्व सिंक झाले!',
      'report_disease': 'रोग सांगा',
      'report_help_text': 'तुमच्या शेतातील रोगाची माहिती देऊन जवळच्या शेतकऱ्यांना मदत करा',
      'select_crop': 'पीक निवडा',
      'select_disease': 'रोग निवडा',
      'submit_report': 'रिपोर्ट पाठवा',
      'report_submitted': 'तुमची रिपोर्ट जवळच्या शेतकऱ्यांना पाठवली!',
      'you': 'तुम्ही',
      'wheat': 'गहू',
      'rice': 'तांदूळ',
      'leaf_curl': 'पान मुडणे',
      'root_rot': 'मूळ कुजणे',
    },
    'te': {
      'nav_scan': 'స్కాన్',
      'nav_result': 'ఫలితం',
      'nav_treat': 'చికిత్స',
      'nav_history': 'చరిత్ర',
      'home_hint': 'ప్రభావిత ఆకును చూపండి',
      'home_gallery': 'గ్యాలరీ',
      'home_take_photo': 'ఫోటో తీయండి',
      'weather_msg': 'ఈరోజు తేమ ఎక్కువ — ఫంగస్ ప్రమాదం',
      'disease_detected': 'వ్యాధి కనుగొనబడింది',
      'found_on': 'కనుగొనబడింది',
      'match': 'మ్యాచ్',
      'needs_attention': 'శ్రద్ధ అవసరం',
      'critical': 'తీవ్రమైన',
      'monitor': 'గమనించండి',
      'healthy': 'ఆరోగ్యం',
      'see_what_to_do': 'ఏమి చేయాలో చూడండి',
      'treatment_plan': 'చికిత్స ప్రణాళిక',
      'what_to_do': 'ఇప్పుడు ఏమి చేయాలి',
      'maintenance_tips': 'నిర్వహణ చిట్కాలు',
      'buy_nearby': 'సమీపంలో కొనండి',
      'get_directions': 'దారి చూడండి',
      'do_today': 'ఈరోజు చేయండి',
      'ongoing': 'కొనసాగించండి',
      'step1': 'ఈరోజు సూర్యాస్తమయానికి ముందు మాంకోజెబ్ పిచికారీ చేయండి',
      'step1_detail': 'లీటరు నీటికి 2.5 గ్రా కలపండి. అన్ని ఆకులపై పిచికారీ చేయండి.',
      'step2': 'ఎక్కువగా ప్రభావితమైన 3-4 ఆకులను తొలగించండి',
      'step2_detail': 'వాటిని కత్తిరించి పొలం నుండి దూరంగా తీసుకెళ్ళండి.',
      'step3': 'మొదలు వద్ద మాత్రమే నీరు పోయండి — ఆకులను తడపకండి',
      'step3_detail': 'డ్రిప్ ఇరిగేషన్ వాడండి. తడి ఆకులు ఫంగస్ పెరగడానికి సహాయపడతాయి.',
      'crop_history': 'పంట చరిత్ర',
      'history_subtitle': 'మీ పొలం ఆరోగ్యం',
      'recent_scans': 'ఇటీవలి స్కాన్లు',
      'scans': 'స్కాన్లు',
      'diseases': 'వ్యాధులు',
      'resolved': 'పరిష్కరించబడింది',
      'status_active': 'సక్రియం',
      'status_fixed': 'సరిచేశారు',
      'status_ok': 'సరే',
      'field_health': 'పొలం ఆరోగ్యం',
      'watch': 'గమనించండి',
      'affected': 'ప్రభావితం',
      'early_blight': 'ఎర్లీ బ్లైట్',
      'early_blight_desc': 'ఈ ఫంగస్ ఆకులపై గుండ్రని గోధుమ మచ్చలు చేస్తుంది.',
      'early_blight_spread': 'తేమ వాతావరణంలో వేగంగా వ్యాపిస్తుంది.',
      'early_blight_urgency': '24 గంటల్లో చర్య తీసుకోండి.',
      'scan_details': 'స్కాన్ వివరాలు',
      'treatment_applied': 'చేసిన చికిత్స',
      'no_treatment': 'చికిత్స నమోదు కాలేదు',
      'view_treatment': 'చికిత్స చూడండి',
      'language': 'భాష',
      'listening': 'వింటున్నాము...',
      'tomato': 'టమాటా',
      'onion': 'ఉల్లిపాయ',
      'soybean': 'సోయాబీన్',
      'cotton': 'పత్తి',
      'late_blight': 'లేట్ బ్లైట్',
      'powdery_mildew': 'పౌడరీ మిల్డ్యూ',
      'bacterial_blight': 'బ్యాక్టీరియల్ బ్లైట్',
      'nav_community': 'ఫీడ్',
      'community_alerts': 'సమాజ హెచ్చరికలు',
      'community_subtitle': 'మీ పొలం సమీపంలో వ్యాధి నివేదికలు',
      'reports_near_you': 'మీకు సమీపంలో వ్యాధి నివేదికలు',
      'this_week_5km': 'ఈ వారం 5 కి.మీ. లోపల',
      'trending_diseases': 'ట్రెండింగ్ వ్యాధులు',
      'recent_reports': 'ఇటీవలి నివేదికలు',
      'your_field': 'మీ పొలం',
      'radius': 'వ్యాసార్ధం',
      'ago': 'క్రితం',
      'spray_schedule': 'పిచికారీ షెడ్యూల్',
      'harvest_window': 'సురక్షిత పంట కోత ~21 రోజుల్లో',
      'track_recovery': 'రికవరీ చూడండి',
      'before': 'ముందు',
      'after': 'తరువాత',
      'drag_to_compare': 'పోల్చడానికి స్లైడర్ లాగండి',
      'offline_mode': 'ఆఫ్‌లైన్ మోడ్',
      'scans_saved': 'స్కాన్లు సేవ్ చేయబడ్డాయి',
      'syncing_scans': 'ఆన్‌లైన్ — స్కాన్లు సింక్ అవుతున్నాయి...',
      'back_online': 'అన్నీ సింక్ అయ్యాయి!',
      'report_disease': 'వ్యాధి నివేదించండి',
      'report_help_text': 'మీ పొలంలో వ్యాధిని నివేదించి సమీపంలోని రైతులకు సహాయం చేయండి',
      'select_crop': 'పంట ఎంచుకోండి',
      'select_disease': 'వ్యాధి ఎంచుకోండి',
      'submit_report': 'నివేదిక పంపండి',
      'report_submitted': 'మీ నివేదిక సమీపంలోని రైతులకు పంపబడింది!',
      'you': 'మీరు',
      'wheat': 'గోధుమ',
      'rice': 'వరి',
      'leaf_curl': 'ఆకు ముడత',
      'root_rot': 'వేరు కుళ్ళు',
    },
    'ta': {
      'nav_scan': 'ஸ்கேன்',
      'nav_result': 'முடிவு',
      'nav_treat': 'சிகிச்சை',
      'nav_history': 'வரலாறு',
      'home_hint': 'பாதிக்கப்பட்ட இலையை காட்டுங்கள்',
      'home_gallery': 'கேலரி',
      'home_take_photo': 'புகைப்படம் எடு',
      'weather_msg': 'இன்று ஈரப்பதம் அதிகம் — பூஞ்சை ஆபத்து',
      'disease_detected': 'நோய் கண்டறியப்பட்டது',
      'found_on': 'கண்டறியப்பட்டது',
      'match': 'பொருத்தம்',
      'needs_attention': 'கவனம் தேவை',
      'critical': 'தீவிரமான',
      'monitor': 'கவனி',
      'healthy': 'ஆரோக்கியம்',
      'see_what_to_do': 'என்ன செய்ய வேண்டும்',
      'treatment_plan': 'சிகிச்சை திட்டம்',
      'what_to_do': 'இப்போது என்ன செய்ய வேண்டும்',
      'maintenance_tips': 'பராமரிப்பு குறிப்புகள்',
      'buy_nearby': 'அருகில் வாங்கவும்',
      'get_directions': 'வழி காட்டு',
      'do_today': 'இன்று செய்',
      'ongoing': 'தொடர்ச்சி',
      'step1': 'இன்று சூரிய அஸ்தமனத்திற்கு முன் மான்கோசெப் தெளிக்கவும்',
      'step1_detail': 'ஒரு லிட்டர் நீரில் 2.5 கிராம் கலக்கவும்.',
      'step2': 'மிகவும் பாதிக்கப்பட்ட 3-4 இலைகளை நீக்கவும்',
      'step2_detail': 'வெட்டி வயலில் இருந்து எடுத்துச் செல்லுங்கள்.',
      'step3': 'அடிப்பகுதியில் மட்டும் நீர் ஊற்றவும்',
      'step3_detail': 'சொட்டு நீர் பாசனம் பயன்படுத்தவும்.',
      'crop_history': 'பயிர் வரலாறு',
      'history_subtitle': 'உங்கள் வயல் ஆரோக்கியம்',
      'recent_scans': 'சமீபத்திய ஸ்கேன்கள்',
      'scans': 'ஸ்கேன்கள்',
      'diseases': 'நோய்கள்',
      'resolved': 'தீர்க்கப்பட்டது',
      'status_active': 'செயலில்',
      'status_fixed': 'சரி',
      'status_ok': 'சரி',
      'field_health': 'வயல் ஆரோக்கியம்',
      'watch': 'கவனி',
      'affected': 'பாதிக்கப்பட்ட',
      'early_blight': 'ஆரம்ப கருகல்',
      'early_blight_desc': 'இந்த பூஞ்சை இலைகளில் வட்ட பழுப்பு புள்ளிகளை உருவாக்குகிறது.',
      'early_blight_spread': 'ஈரப்பதமான வானிலையில் வேகமாக பரவுகிறது.',
      'early_blight_urgency': '24 மணி நேரத்தில் நடவடிக்கை எடுக்கவும்.',
      'scan_details': 'ஸ்கேன் விவரங்கள்',
      'treatment_applied': 'செய்த சிகிச்சை',
      'no_treatment': 'சிகிச்சை பதிவு இல்லை',
      'view_treatment': 'சிகிச்சை பார்க்க',
      'language': 'மொழி',
      'listening': 'கேட்கிறது...',
      'tomato': 'தக்காளி',
      'onion': 'வெங்காயம்',
      'soybean': 'சோயாபீன்',
      'cotton': 'பருத்தி',
      'late_blight': 'லேட் பிளைட்',
      'powdery_mildew': 'பவுடரி மில்டியூ',
      'bacterial_blight': 'பாக்டீரியல் பிளைட்',
      'nav_community': 'ஊட்டம்',
      'community_alerts': 'சமூக எச்சரிக்கைகள்',
      'community_subtitle': 'உங்கள் பண்ணை அருகில் நோய் அறிக்கைகள்',
      'reports_near_you': 'உங்களுக்கு அருகில் நோய் அறிக்கைகள்',
      'this_week_5km': 'இந்த வாரம் 5 கி.மீ. க்குள்',
      'trending_diseases': 'நோய் போக்குகள்',
      'recent_reports': 'சமீபத்திய அறிக்கைகள்',
      'your_field': 'உங்கள் வயல்',
      'radius': 'ஆரை',
      'ago': 'முன்',
      'spray_schedule': 'தெளிப்பு அட்டவணை',
      'harvest_window': 'பாதுகாப்பான அறுவடை ~21 நாட்களில்',
      'track_recovery': 'மீட்பு பார்க்க',
      'before': 'முன்',
      'after': 'பின்',
      'drag_to_compare': 'ஒப்பிட்டு பார்க்க ஸ்லைடரை இழுக்கவும்',
      'offline_mode': 'ஆஃப்லைன் பயன்முறை',
      'scans_saved': 'ஸ்கேன்கள் சேமிக்கப்பட்டன',
      'syncing_scans': 'ஆன்லைன் — ஸ்கேன்கள் ஒத்திசைக்கப்படுகின்றன...',
      'back_online': 'அனைத்தும் ஒத்திசைவு ஆனது!',
      'report_disease': 'நோய் புகாரளி',
      'report_help_text': 'உங்கள் வயலில் நோயை புகாரளித்து அருகிலுள்ள விவசாயிகளுக்கு உதவுங்கள்',
      'select_crop': 'பயிர் தேர்ந்தெடு',
      'select_disease': 'நோய் தேர்ந்தெடு',
      'submit_report': 'புகார் அனுப்பு',
      'report_submitted': 'உங்கள் புகார் அருகிலுள்ள விவசாயிகளுக்கு அனுப்பப்பட்டது!',
      'you': 'நீங்கள்',
      'wheat': 'கோதுமை',
      'rice': 'அரிசி',
      'leaf_curl': 'இலை சுருட்டை',
      'root_rot': 'வேர் அழுகல்',
    },
  };
}
